export const MAKES: string[] = [
  'Ford',
  'Chevrolet',
  'GMC',
  'Jeep',
  'Dodge',
  'Ram',
  'Tesla',
  'Toyota',
  'Honda',
  'Nissan',
  'Subaru',
  'Hyundai',
  'Kia',
  'BMW',
  'Mercedes-Benz',
  'Audi',
  'Volkswagen',
];

export const MODELS_BY_MAKE: Record<string, string[]> = {
  Ford: [
    'Bronco',
    'Bronco Sport',
    'EcoSport',
    'Edge',
    'Escape',
    'Expedition',
    'Explorer',
    'F-150',
    'F-150 Lightning',
    'F-250 Super Duty',
    'F-350 Super Duty',
    'Fiesta',
    'Flex',
    'Focus',
    'Fusion',
    'Maverick',
    'Mustang',
    'Mustang Mach-E',
    'Ranger',
    'Taurus',
    'Transit',
    'Transit Connect',
  ],
  Chevrolet: [
    'Blazer',
    'Bolt EUV',
    'Bolt EV',
    'Camaro',
    'Colorado',
    'Corvette',
    'Cruze',
    'Equinox',
    'Express',
    'Impala',
    'Malibu',
    'Silverado 1500',
    'Silverado 2500HD',
    'Silverado 3500HD',
    'Sonic',
    'Spark',
    'Suburban',
    'Tahoe',
    'Trailblazer',
    'Traverse',
    'Trax',
  ],
  GMC: [
    'Acadia',
    'Canyon',
    'Hummer EV Pickup',
    'Hummer EV SUV',
    'Savana',
    'Sierra 1500',
    'Sierra 2500HD',
    'Sierra 3500HD',
    'Terrain',
    'Yukon',
    'Yukon XL',
  ],
  Jeep: [
    'Cherokee',
    'Commander',
    'Compass',
    'Gladiator',
    'Grand Cherokee',
    'Grand Cherokee L',
    'Grand Wagoneer',
    'Liberty',
    'Patriot',
    'Renegade',
    'Wagoneer',
    'Wrangler',
    'Wrangler 4xe',
  ],
  Dodge: [
    'Challenger',
    'Charger',
    'Dart',
    'Durango',
    'Grand Caravan',
    'Hornet',
    'Journey',
    'Viper',
  ],
  Ram: ['1500', '1500 Classic', '2500', '3500', 'ProMaster', 'ProMaster City'],
  Tesla: ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster'],
  Toyota: [
    '4Runner',
    'Avalon',
    'bZ4X',
    'Camry',
    'C-HR',
    'Corolla',
    'Corolla Cross',
    'GR86',
    'Grand Highlander',
    'Highlander',
    'Land Cruiser',
    'Prius',
    'Prius Prime',
    'RAV4',
    'RAV4 Prime',
    'Sequoia',
    'Sienna',
    'Supra',
    'Tacoma',
    'Tundra',
    'Venza',
    'Yaris',
  ],
  Honda: [
    'Accord',
    'Civic',
    'Civic Type R',
    'CR-V',
    'Crosstour',
    'Element',
    'Fit',
    'HR-V',
    'Insight',
    'Odyssey',
    'Passport',
    'Pilot',
    'Prologue',
    'Ridgeline',
  ],
  Nissan: [
    '370Z',
    'Altima',
    'Ariya',
    'Armada',
    'Frontier',
    'GT-R',
    'Juke',
    'Kicks',
    'Leaf',
    'Maxima',
    'Murano',
    'Pathfinder',
    'Quest',
    'Rogue',
    'Rogue Sport',
    'Sentra',
    'Titan',
    'Titan XD',
    'Versa',
    'Xterra',
    'Z',
  ],
  Subaru: [
    'Ascent',
    'Baja',
    'BRZ',
    'Crosstrek',
    'Forester',
    'Impreza',
    'Legacy',
    'Outback',
    'Solterra',
    'Tribeca',
    'WRX',
    'WRX STI',
  ],
  Hyundai: [
    'Accent',
    'Azera',
    'Elantra',
    'Ioniq 5',
    'Ioniq 6',
    'Kona',
    'Nexo',
    'Palisade',
    'Santa Cruz',
    'Santa Fe',
    'Sonata',
    'Tucson',
    'Veloster',
    'Venue',
    'Veracruz',
  ],
  Kia: [
    'Cadenza',
    'Carnival',
    'EV6',
    'EV9',
    'Forte',
    'K5',
    'Niro',
    'Optima',
    'Rio',
    'Sedona',
    'Seltos',
    'Sorento',
    'Soul',
    'Sportage',
    'Stinger',
    'Telluride',
  ],
  BMW: [
    '2 Series',
    '3 Series',
    '4 Series',
    '5 Series',
    '7 Series',
    '8 Series',
    'i3',
    'i4',
    'i5',
    'i7',
    'iX',
    'M2',
    'M3',
    'M4',
    'M5',
    'M8',
    'X1',
    'X2',
    'X3',
    'X4',
    'X5',
    'X6',
    'X7',
    'Z4',
  ],
  'Mercedes-Benz': [
    'A-Class',
    'AMG GT',
    'C-Class',
    'CLA',
    'CLS',
    'E-Class',
    'EQB',
    'EQE',
    'EQS',
    'G-Class',
    'GLA',
    'GLB',
    'GLC',
    'GLE',
    'GLS',
    'Metris',
    'S-Class',
    'SL',
    'Sprinter',
  ],
  Audi: [
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'e-tron GT',
    'Q3',
    'Q4 e-tron',
    'Q5',
    'Q7',
    'Q8',
    'R8',
    'RS 3',
    'RS 5',
    'RS 7',
    'S3',
    'S4',
    'S5',
    'TT',
  ],
  Volkswagen: [
    'Arteon',
    'Atlas',
    'Atlas Cross Sport',
    'Beetle',
    'CC',
    'Golf',
    'Golf GTI',
    'Golf R',
    'ID.4',
    'ID. Buzz',
    'Jetta',
    'Passat',
    'Taos',
    'Tiguan',
    'Touareg',
  ],
};

export const TRIMS_BY_MAKE: Record<string, string[]> = {
  Ford: [
    'XL',
    'XLT',
    'STX',
    'Lariat',
    'King Ranch',
    'Platinum',
    'Limited',
    'Tremor',
    'Raptor',
    'Raptor R',
    'S',
    'SE',
    'SEL',
    'Titanium',
    'ST',
    'ST-Line',
    'GT',
    'Mach 1',
    'Big Bend',
    'Black Diamond',
    'Outer Banks',
    'Badlands',
    'Wildtrak',
    'Heritage',
    'Base',
    'Premium',
    'California Route 1',
    'Rally',
    'GT Performance',
  ],
  Chevrolet: [
    'WT',
    'LS',
    'LT',
    'RS',
    'Custom',
    'Custom Trail Boss',
    'LT Trail Boss',
    'Z71',
    'ZR2',
    'ZR2 Bison',
    'Premier',
    'High Country',
    'Activ',
    'RST',
    'SS',
    '1LT',
    '2LT',
    '3LT',
    'Stingray',
    'Z06',
    'E-Ray',
    'ZR1',
  ],
  GMC: [
    'Pro',
    'SLE',
    'SLT',
    'Elevation',
    'AT4',
    'AT4X',
    'AT4X AEV',
    'Denali',
    'Denali Ultimate',
    'EV Edition 1',
    'Base',
  ],
  Jeep: [
    'Sport',
    'Sport S',
    'Willys',
    'Willys Sport',
    'Freedom',
    'Altitude',
    'Latitude',
    'Latitude Lux',
    'Laredo',
    'Limited',
    'Rubicon',
    'Rubicon 392',
    'Rubicon X',
    'Sahara',
    'Mojave',
    'Overland',
    'Summit',
    'Summit Reserve',
    'Trailhawk',
    'High Altitude',
    'Trackhawk',
    'Series I',
    'Series II',
    'Series III',
  ],
  Dodge: [
    'SXT',
    'SXT Plus',
    'GT',
    'GT Plus',
    'R/T',
    'R/T Plus',
    'R/T Scat Pack',
    'Scat Pack Widebody',
    'SRT Hellcat',
    'SRT Hellcat Redeye',
    'SRT Demon 170',
    'Citadel',
    'Pursuit',
    'Plus',
    'Blacktop',
    'Base',
  ],
  Ram: [
    'Tradesman',
    'HFE',
    'Big Horn',
    'Lone Star',
    'Laramie',
    'Laramie Longhorn',
    'Rebel',
    'Rebel X',
    'Warlock',
    'Limited',
    'Limited Longhorn',
    'TRX',
    'RHO',
    'Power Wagon',
    'Tungsten',
  ],
  Tesla: [
    'Standard Range',
    'Standard Range Plus',
    'Long Range',
    'Long Range RWD',
    'Long Range AWD',
    'Performance',
    'Plaid',
    'Plaid+',
    'Cyberbeast',
    'Foundation Series',
    'Launch Series',
  ],
  Toyota: [
    'L',
    'LE',
    'XLE',
    'SE',
    'XSE',
    'SE Nightshade',
    'Limited',
    'Platinum',
    'Capstone',
    '1794 Edition',
    'SR',
    'SR5',
    'TRD Sport',
    'TRD Off-Road',
    'TRD Pro',
    'Trailhunter',
    'Woodland Edition',
    'Hybrid',
    'Prime',
    'Base',
    'XSE Premium',
  ],
  Honda: [
    'LX',
    'Sport',
    'Sport Hybrid',
    'EX',
    'EX-L',
    'Sport Touring',
    'Touring',
    'Elite',
    'Si',
    'Type R',
    'TrailSport',
    'Black Edition',
    'RTL',
    'RTL-E',
    'Base',
  ],
  Nissan: [
    'S',
    'SV',
    'SL',
    'SR',
    'SR Premium',
    'Platinum',
    'Platinum Reserve',
    'Midnight Edition',
    'PRO-4X',
    'Rock Creek',
    'NISMO',
    'Venture',
    'Engage',
    'Evolve',
    'Empower',
    'Base',
  ],
  Subaru: [
    'Base',
    'Premium',
    'Sport',
    'Onyx Edition',
    'Onyx Edition XT',
    'Limited',
    'Limited XT',
    'Touring',
    'Touring XT',
    'Wilderness',
    'tS',
    'TR',
    'Convenience',
    'Anniversary Edition',
  ],
  Hyundai: [
    'SE',
    'SEL',
    'SEL Convenience',
    'SEL Premium',
    'Limited',
    'N Line',
    'N',
    'Calligraphy',
    'Blue',
    'Blue SE',
    'XRT',
    'Night Edition',
    'Base',
  ],
  Kia: [
    'LX',
    'S',
    'EX',
    'EX Premium',
    'GT-Line',
    'SX',
    'SX Prestige',
    'X-Line',
    'X-Pro',
    'X-Pro Prestige',
    'GT',
    'GT1',
    'GT2',
    'Wind',
    'Light',
    'Land',
    'Wolf',
    'Base',
  ],
  BMW: [
    'Base',
    'sDrive',
    'xDrive',
    'M Sport',
    'M Sport Pro',
    'Competition',
    'Competition xDrive',
    'CS',
    'CSL',
    'Alpina',
    'M Performance',
    'Luxury',
    'M Sport Package',
  ],
  'Mercedes-Benz': [
    'Base',
    '4MATIC',
    'AMG Line',
    'Premium',
    'Exclusive',
    'Pinnacle',
    'AMG',
    'AMG S',
    'Maybach',
    'Night Edition',
    'Cargo',
    'Passenger',
    'Crew',
    'Edition 1',
  ],
  Audi: [
    'Premium',
    'Premium Plus',
    'Prestige',
    'S line',
    'Black Optic',
    'Komfort',
    'Progressiv',
    'Technik',
    'Base',
    'RS Design',
  ],
  Volkswagen: [
    'S',
    'SE',
    'SE R-Line Black',
    'SEL',
    'SEL R-Line',
    'SEL Premium R-Line',
    'Comfortline',
    'Highline',
    'Autobahn',
    'Pro',
    'Pro S',
    'Pro S Plus',
    '1st Edition',
    'Peak Edition',
    'Base',
  ],
};

export const TRANSMISSION_TYPES: string[] = ['Automatic', 'Manual', 'CVT', 'DCT', 'Single-Speed'];
